### ISSUE TITLE
Import VR-Sim

### ISSUE THREAD

**Issue by DieSlower** [acidrainstudios/TrueReality#1]
Import the VR-Sim project and restructure it into the new True Reality engine base. 

VR-Sim is an engine @DieSlower built many years ago. Some modules of it were built for Stevens Institute of Technology and are partially owned by it.
The core VR-Sim engine is developed and owned by DieSlower and with his permission is going to be converted into an LGPL project and continue its development under a new name.

**Comment by DieSlower** [comment]
VR-Sim is an engine @DieSlower built many years ago. Some modules of it were built for Stevens Institute of Technology and are partially owned by it. 
The core VR-Sim engine is developed and owned by DieSlower and with his permission is going to be converted into an LGPL project and continue its development under a new name.

**Comment by acidrainstudios** [comment]
Kamino cloned this issue to acidrainstudios/TrueRealityTemp
