### ISSUE TITLE
CMake Hint Wildcards Not Working

### ISSUE THREAD

**Issue by tylergaravaglia** [acidrainstudios/TrueReality#123]
When building with CMake 3.11.2, the configure scripts don't find libraries for OSG, OpenThreads, GoogleTest, or jsoncpp. All the include folders are found fine. It seems the * wildcards used to look for either lib or lib64 aren't working as expected.

**Comment by DieSlower** [comment]
Tested the fix on CO7.6 with OSG libraries moved to a different folder and OSG_ROOT set to it. 
Both OpenThreads and OSG was found.
